#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';

const REQUIRED_EXPORTS_BY_PROFILE = {
  validation: [
    'memory',
    'lmt_wasm_scratch_ptr',
    'lmt_wasm_scratch_size',
    'lmt_svg_compat_kind_count',
    'lmt_svg_compat_kind_name',
    'lmt_svg_compat_kind_directory',
    'lmt_svg_compat_image_count',
    'lmt_svg_compat_image_name',
    'lmt_svg_compat_generate',
  ],
  full_demo: [
    'memory',
    'lmt_pcs_from_list',
    'lmt_pcs_to_list',
    'lmt_pcs_cardinality',
    'lmt_pcs_transpose',
    'lmt_pcs_invert',
    'lmt_pcs_complement',
    'lmt_pcs_is_subset',
    'lmt_prime_form',
    'lmt_forte_prime',
    'lmt_is_cluster_free',
    'lmt_evenness_distance',
    'lmt_scale',
    'lmt_mode',
    'lmt_counterpoint_max_voices',
    'lmt_counterpoint_history_capacity',
    'lmt_counterpoint_rule_profile_count',
    'lmt_counterpoint_rule_profile_name',
    'lmt_sizeof_voiced_state',
    'lmt_sizeof_voiced_history',
    'lmt_sizeof_next_step_suggestion',
    'lmt_cadence_destination_count',
    'lmt_cadence_destination_name',
    'lmt_suspension_state_count',
    'lmt_suspension_state_name',
    'lmt_sizeof_cadence_destination_score',
    'lmt_sizeof_suspension_machine_summary',
    'lmt_voiced_history_reset',
    'lmt_build_voiced_state',
    'lmt_voiced_history_push',
    'lmt_classify_motion',
    'lmt_evaluate_motion_profile',
    'lmt_rank_next_steps',
    'lmt_rank_cadence_destinations',
    'lmt_analyze_suspension_machine',
    'lmt_next_step_reason_count',
    'lmt_next_step_reason_name',
    'lmt_next_step_warning_count',
    'lmt_next_step_warning_name',
    'lmt_mode_spelling_quality',
    'lmt_spell_note',
    'lmt_spell_note_parts',
    'lmt_chord',
    'lmt_chord_name',
    'lmt_roman_numeral',
    'lmt_roman_numeral_parts',
    'lmt_fret_to_midi',
    'lmt_fret_to_midi_n',
    'lmt_midi_to_fret_positions',
    'lmt_midi_to_fret_positions_n',
    'lmt_generate_voicings_n',
    'lmt_rank_context_suggestions',
    'lmt_preferred_voicing_n',
    'lmt_pitch_class_guide_n',
    'lmt_frets_to_url_n',
    'lmt_url_to_frets_n',
    'lmt_svg_clock_optc',
    'lmt_svg_optic_k_group',
    'lmt_svg_evenness_chart',
    'lmt_svg_evenness_field',
    'lmt_svg_fret',
    'lmt_svg_fret_n',
    'lmt_svg_fret_tuned_n',
    'lmt_svg_chord_staff',
    'lmt_svg_key_staff',
    'lmt_svg_keyboard',
    'lmt_svg_piano_staff',
    'lmt_raster_is_enabled',
    'lmt_bitmap_clock_optc_rgba',
    'lmt_bitmap_optic_k_group_rgba',
    'lmt_bitmap_evenness_chart_rgba',
    'lmt_bitmap_evenness_field_rgba',
    'lmt_bitmap_fret_rgba',
    'lmt_bitmap_fret_n_rgba',
    'lmt_bitmap_fret_tuned_n_rgba',
    'lmt_bitmap_chord_staff_rgba',
    'lmt_bitmap_key_staff_rgba',
    'lmt_bitmap_keyboard_rgba',
    'lmt_bitmap_piano_staff_rgba',
    'lmt_wasm_scratch_ptr',
    'lmt_wasm_scratch_size',
    'lmt_svg_compat_kind_count',
    'lmt_svg_compat_kind_name',
    'lmt_svg_compat_kind_directory',
    'lmt_svg_compat_image_count',
    'lmt_svg_compat_image_name',
    'lmt_svg_compat_generate',
  ],
  gallery: [
    'memory',
    'lmt_pcs_from_list',
    'lmt_pcs_to_list',
    'lmt_pcs_cardinality',
    'lmt_pcs_transpose',
    'lmt_pcs_invert',
    'lmt_pcs_complement',
    'lmt_prime_form',
    'lmt_forte_prime',
    'lmt_is_cluster_free',
    'lmt_evenness_distance',
    'lmt_scale',
    'lmt_mode',
    'lmt_counterpoint_max_voices',
    'lmt_counterpoint_history_capacity',
    'lmt_counterpoint_rule_profile_count',
    'lmt_counterpoint_rule_profile_name',
    'lmt_sizeof_voiced_state',
    'lmt_sizeof_voiced_history',
    'lmt_sizeof_next_step_suggestion',
    'lmt_cadence_destination_count',
    'lmt_cadence_destination_name',
    'lmt_suspension_state_count',
    'lmt_suspension_state_name',
    'lmt_sizeof_cadence_destination_score',
    'lmt_sizeof_suspension_machine_summary',
    'lmt_voiced_history_reset',
    'lmt_build_voiced_state',
    'lmt_voiced_history_push',
    'lmt_classify_motion',
    'lmt_evaluate_motion_profile',
    'lmt_rank_next_steps',
    'lmt_rank_cadence_destinations',
    'lmt_analyze_suspension_machine',
    'lmt_next_step_reason_count',
    'lmt_next_step_reason_name',
    'lmt_next_step_warning_count',
    'lmt_next_step_warning_name',
    'lmt_mode_spelling_quality',
    'lmt_spell_note',
    'lmt_spell_note_parts',
    'lmt_chord',
    'lmt_chord_name',
    'lmt_roman_numeral',
    'lmt_roman_numeral_parts',
    'lmt_fret_to_midi_n',
    'lmt_midi_to_fret_positions_n',
    'lmt_generate_voicings_n',
    'lmt_rank_context_suggestions',
    'lmt_preferred_voicing_n',
    'lmt_pitch_class_guide_n',
    'lmt_frets_to_url_n',
    'lmt_url_to_frets_n',
    'lmt_svg_clock_optc',
    'lmt_svg_optic_k_group',
    'lmt_svg_evenness_chart',
    'lmt_svg_evenness_field',
    'lmt_svg_fret',
    'lmt_svg_fret_n',
    'lmt_svg_fret_tuned_n',
    'lmt_svg_chord_staff',
    'lmt_svg_key_staff',
    'lmt_svg_keyboard',
    'lmt_svg_piano_staff',
    'lmt_bitmap_clock_optc_rgba',
    'lmt_bitmap_optic_k_group_rgba',
    'lmt_bitmap_evenness_chart_rgba',
    'lmt_bitmap_evenness_field_rgba',
    'lmt_bitmap_fret_rgba',
    'lmt_bitmap_fret_n_rgba',
    'lmt_bitmap_fret_tuned_n_rgba',
    'lmt_bitmap_chord_staff_rgba',
    'lmt_bitmap_key_staff_rgba',
    'lmt_bitmap_keyboard_rgba',
    'lmt_bitmap_piano_staff_rgba',
  ],
  scaled_render_parity: [
    'memory',
    'lmt_wasm_scratch_ptr',
    'lmt_wasm_scratch_size',
    'lmt_svg_compat_kind_count',
    'lmt_svg_compat_kind_name',
    'lmt_svg_compat_kind_directory',
    'lmt_svg_compat_image_count',
    'lmt_svg_compat_image_name',
    'lmt_svg_compat_generate',
    'lmt_bitmap_proof_scale_numerator',
    'lmt_bitmap_proof_scale_denominator',
    'lmt_bitmap_compat_kind_supported',
    'lmt_bitmap_compat_candidate_backend_name',
    'lmt_bitmap_compat_target_width_scaled',
    'lmt_bitmap_compat_target_width',
    'lmt_bitmap_compat_target_height_scaled',
    'lmt_bitmap_compat_target_height',
    'lmt_bitmap_compat_required_rgba_bytes_scaled',
    'lmt_bitmap_compat_required_rgba_bytes',
    'lmt_bitmap_compat_render_candidate_rgba_scaled',
    'lmt_bitmap_compat_render_candidate_rgba',
    'lmt_bitmap_compat_render_reference_svg_rgba_scaled',
    'lmt_bitmap_compat_render_reference_svg_rgba',
  ],
  native_rgba_proof: [
    'memory',
    'lmt_wasm_scratch_ptr',
    'lmt_wasm_scratch_size',
    'lmt_svg_compat_kind_count',
    'lmt_svg_compat_kind_name',
    'lmt_svg_compat_kind_directory',
    'lmt_svg_compat_image_count',
    'lmt_svg_compat_image_name',
    'lmt_bitmap_proof_scale_numerator',
    'lmt_bitmap_proof_scale_denominator',
    'lmt_bitmap_compat_kind_supported',
    'lmt_bitmap_compat_candidate_backend_name',
    'lmt_bitmap_compat_target_width_scaled',
    'lmt_bitmap_compat_target_width',
    'lmt_bitmap_compat_target_height_scaled',
    'lmt_bitmap_compat_target_height',
    'lmt_bitmap_compat_required_rgba_bytes_scaled',
    'lmt_bitmap_compat_required_rgba_bytes',
    'lmt_bitmap_compat_render_candidate_rgba_scaled',
    'lmt_bitmap_compat_render_candidate_rgba',
    'lmt_bitmap_compat_render_reference_svg_rgba_scaled',
    'lmt_bitmap_compat_render_reference_svg_rgba',
  ],
};

function parseArg(flag, fallback = null) {
  const idx = process.argv.indexOf(flag);
  if (idx === -1) return fallback;
  if (idx + 1 >= process.argv.length) {
    throw new Error(`missing value for ${flag}`);
  }
  return process.argv[idx + 1];
}

async function main() {
  const wasmPathArg = parseArg('--wasm', 'zig-out/wasm-demo/libmusictheory.wasm');
  const profile = parseArg('--profile', 'validation');
  if (!(profile in REQUIRED_EXPORTS_BY_PROFILE)) {
    throw new Error(`unknown export profile '${profile}'`);
  }
  const required = REQUIRED_EXPORTS_BY_PROFILE[profile];
  const wasmPath = path.resolve(process.cwd(), wasmPathArg);

  if (!fs.existsSync(wasmPath)) {
    throw new Error(`wasm not found: ${wasmPath}`);
  }

  const bytes = fs.readFileSync(wasmPath);
  const mod = await WebAssembly.compile(bytes);
  const exports = WebAssembly.Module.exports(mod).map((entry) => entry.name);
  const exportSet = new Set(exports);

  const missing = required.filter((name) => !exportSet.has(name));
  if (missing.length > 0) {
    console.error(
      `missing required exports for profile '${profile}' (${missing.length}): ${missing.join(', ')}`,
    );
    process.exit(1);
  }

  console.log(`wasm exports ok: profile=${profile}, required=${required.length}, actual=${exports.length}`);
}

main().catch((err) => {
  console.error(err.message || String(err));
  process.exit(1);
});
