#!/usr/bin/env python3
"""Generate compact xz-packed harmonious compat image-name payload.

Input:
  tmp/harmoniousapp.net/<kind>/*.svg

Output:
  src/generated/harmonious_name_pack_xz.zig
"""

from __future__ import annotations

import argparse
import lzma
import struct
from pathlib import Path


KIND_SPECS = (
    ("vert-text-black", "vert-text-black", True),
    ("even", "even", True),
    ("scale", "scale", True),
    ("opc", "opc", True),
    ("oc", "oc", True),
    ("optc", "optc", True),
    ("eadgbe", "eadgbe", True),
    ("center-square-text", "center-square-text", True),
    ("wide-chord", "wide-chord", True),
    ("chord-clipped", "chord-clipped", True),
    ("grand-chord", "grand-chord", True),
    ("majmin/modes", "majmin", False),
    ("majmin/scales", "majmin", False),
    ("chord", "chord", True),
    ("vert-text-b2t-black", "vert-text-b2t-black", True),
)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--root", default="tmp/harmoniousapp.net", help="harmoniousapp reference root")
    p.add_argument(
        "--out",
        default="src/generated/harmonious_name_pack_xz.zig",
        help="output Zig module",
    )
    return p.parse_args()


def read_kind_names(root: Path, rel_dir: str, collect: bool) -> list[str]:
    if not collect:
        return []

    target = root / rel_dir
    if not target.is_dir():
        raise RuntimeError(f"missing directory: {target}")

    names = sorted({p.name for p in target.glob("*.svg") if p.is_file()})
    return names


def encode_pack(per_kind_names: list[list[str]]) -> bytes:
    counts = [len(names) for names in per_kind_names]
    total_names = sum(counts)

    out = bytearray()
    out.extend(b"HNP1\0\0\0\0")
    out.extend(struct.pack("<I", len(per_kind_names)))
    out.extend(struct.pack("<I", total_names))

    for count in counts:
        out.extend(struct.pack("<I", count))

    for names in per_kind_names:
        for name in names:
            raw = name.encode("utf-8")
            if len(raw) > 0xFFFF:
                raise RuntimeError(f"name too long for u16 length field: {name}")
            out.extend(struct.pack("<H", len(raw)))
            out.extend(raw)

    return bytes(out)


def zig_array(name: str, payload: bytes) -> str:
    lines = [f"pub const {name} = [_]u8{{\n"]
    for i in range(0, len(payload), 16):
        chunk = payload[i : i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
    lines.append("};\n")
    return "".join(lines)


def main() -> int:
    args = parse_args()
    root = Path(args.root)
    out = Path(args.out)

    per_kind_names = [read_kind_names(root, rel_dir, collect) for _, rel_dir, collect in KIND_SPECS]
    counts = [len(names) for names in per_kind_names]
    total_names = sum(counts)

    raw = encode_pack(per_kind_names)
    packed = lzma.compress(raw, format=lzma.FORMAT_XZ, preset=9)

    kind_order = ", ".join(f'"{api_name}"' for api_name, _, _ in KIND_SPECS)
    out_text = [
        "// Auto-generated by scripts/generate_harmonious_name_pack.py",
        "// Compact xz-packed image-name manifest for harmonious SVG compatibility.",
        "// DO NOT EDIT MANUALLY.",
        "",
        f"pub const KIND_COUNT: usize = {len(KIND_SPECS)};",
        f"pub const TOTAL_NAME_COUNT: usize = {total_names};",
        f"pub const PACK_RAW_LEN: usize = {len(raw)};",
        "pub const KIND_API_ORDER = [_][]const u8{ " + kind_order + " };",
        "pub const KIND_IMAGE_COUNTS = [_]u32{ " + ", ".join(str(c) for c in counts) + " };",
        "",
        zig_array("PACK_XZ", packed),
    ]

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(out_text), encoding="utf-8")

    print(
        "wrote",
        out,
        f"(kinds={len(KIND_SPECS)}, names={total_names}, raw={len(raw)}, xz={len(packed)})",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
