#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REF_ROOT="$ROOT_DIR/tmp/harmoniousapp.net"
OUT="$ROOT_DIR/src/generated/harmonious_manifest.zig"
TMP="$OUT.tmp"

mkdir -p "$(dirname "$OUT")"

emit_names() {
  local var_name="$1"
  local rel_dir="$2"
  local prefix_filter="${3:-}"

  printf 'pub const %s = [_][]const u8{\n' "$var_name" >> "$TMP"

  if [ -d "$REF_ROOT/$rel_dir" ]; then
    local names
    if [ -n "$prefix_filter" ]; then
      names=$(find "$REF_ROOT/$rel_dir" -type f -name '*.svg' -exec basename {} \; | grep "^$prefix_filter" | sort -u)
    else
      names=$(find "$REF_ROOT/$rel_dir" -type f -name '*.svg' -exec basename {} \; | sort -u)
    fi

    if [ -n "$names" ]; then
      while IFS= read -r one; do
        printf '    "%s",\n' "$one" >> "$TMP"
      done <<< "$names"
    fi
  fi

  printf '};\n\n' >> "$TMP"
}

cat > "$TMP" <<'HEADER'
// Auto-generated by scripts/generate_harmonious_manifest.sh
// Source: tmp/harmoniousapp.net/* SVG filenames

pub const KindId = enum(u8) {
    vert_text_black,
    even,
    scale,
    opc,
    oc,
    optc,
    eadgbe,
    center_square_text,
    wide_chord,
    chord_clipped,
    grand_chord,
    majmin_modes,
    majmin_scales,
    chord,
    vert_text_b2t_black,
};

pub const KindInfo = struct {
    id: KindId,
    api_name: []const u8,
    directory: []const u8,
    names: []const []const u8,
};

HEADER

emit_names "VERT_TEXT_BLACK_NAMES" "vert-text-black"
emit_names "EVEN_NAMES" "even"
emit_names "SCALE_NAMES" "scale"
emit_names "OPC_NAMES" "opc"
emit_names "OC_NAMES" "oc"
emit_names "OPTC_NAMES" "optc"
emit_names "EADGBE_NAMES" "eadgbe"
emit_names "CENTER_SQUARE_TEXT_NAMES" "center-square-text"
emit_names "WIDE_CHORD_NAMES" "wide-chord"
emit_names "CHORD_CLIPPED_NAMES" "chord-clipped"
emit_names "GRAND_CHORD_NAMES" "grand-chord"
emit_names "MAJMIN_MODES_NAMES" "majmin" "modes,"
emit_names "MAJMIN_SCALES_NAMES" "majmin" "scales,"
emit_names "CHORD_NAMES" "chord"
emit_names "VERT_TEXT_B2T_BLACK_NAMES" "vert-text-b2t-black"

cat >> "$TMP" <<'FOOTER'
pub const ALL_KINDS = [_]KindInfo{
    .{ .id = .vert_text_black, .api_name = "vert-text-black", .directory = "vert-text-black", .names = &VERT_TEXT_BLACK_NAMES },
    .{ .id = .even, .api_name = "even", .directory = "even", .names = &EVEN_NAMES },
    .{ .id = .scale, .api_name = "scale", .directory = "scale", .names = &SCALE_NAMES },
    .{ .id = .opc, .api_name = "opc", .directory = "opc", .names = &OPC_NAMES },
    .{ .id = .oc, .api_name = "oc", .directory = "oc", .names = &OC_NAMES },
    .{ .id = .optc, .api_name = "optc", .directory = "optc", .names = &OPTC_NAMES },
    .{ .id = .eadgbe, .api_name = "eadgbe", .directory = "eadgbe", .names = &EADGBE_NAMES },
    .{ .id = .center_square_text, .api_name = "center-square-text", .directory = "center-square-text", .names = &CENTER_SQUARE_TEXT_NAMES },
    .{ .id = .wide_chord, .api_name = "wide-chord", .directory = "wide-chord", .names = &WIDE_CHORD_NAMES },
    .{ .id = .chord_clipped, .api_name = "chord-clipped", .directory = "chord-clipped", .names = &CHORD_CLIPPED_NAMES },
    .{ .id = .grand_chord, .api_name = "grand-chord", .directory = "grand-chord", .names = &GRAND_CHORD_NAMES },
    .{ .id = .majmin_modes, .api_name = "majmin/modes", .directory = "majmin", .names = &MAJMIN_MODES_NAMES },
    .{ .id = .majmin_scales, .api_name = "majmin/scales", .directory = "majmin", .names = &MAJMIN_SCALES_NAMES },
    .{ .id = .chord, .api_name = "chord", .directory = "chord", .names = &CHORD_NAMES },
    .{ .id = .vert_text_b2t_black, .api_name = "vert-text-b2t-black", .directory = "vert-text-b2t-black", .names = &VERT_TEXT_B2T_BLACK_NAMES },
};
FOOTER

mv "$TMP" "$OUT"
echo "Wrote $OUT"
