const pcs = @import("pitch_class_set.zig");

pub const ForteNumber = struct {
    cardinality: u4,
    ordinal: u8,
    is_z: bool,
};

pub const ForteEntry = struct {
    prime: pcs.PitchClassSet,
    number: ForteNumber,
};

pub const ENTRIES = [_]ForteEntry{
    .{ .prime = 7, .number = .{ .cardinality = 3, .ordinal = 1, .is_z = false } },
    .{ .prime = 11, .number = .{ .cardinality = 3, .ordinal = 2, .is_z = false } },
    .{ .prime = 19, .number = .{ .cardinality = 3, .ordinal = 3, .is_z = false } },
    .{ .prime = 35, .number = .{ .cardinality = 3, .ordinal = 4, .is_z = false } },
    .{ .prime = 67, .number = .{ .cardinality = 3, .ordinal = 5, .is_z = false } },
    .{ .prime = 21, .number = .{ .cardinality = 3, .ordinal = 6, .is_z = false } },
    .{ .prime = 37, .number = .{ .cardinality = 3, .ordinal = 7, .is_z = false } },
    .{ .prime = 69, .number = .{ .cardinality = 3, .ordinal = 8, .is_z = false } },
    .{ .prime = 133, .number = .{ .cardinality = 3, .ordinal = 9, .is_z = false } },
    .{ .prime = 73, .number = .{ .cardinality = 3, .ordinal = 10, .is_z = false } },
    .{ .prime = 137, .number = .{ .cardinality = 3, .ordinal = 11, .is_z = false } },
    .{ .prime = 273, .number = .{ .cardinality = 3, .ordinal = 12, .is_z = false } },
    .{ .prime = 15, .number = .{ .cardinality = 4, .ordinal = 1, .is_z = false } },
    .{ .prime = 23, .number = .{ .cardinality = 4, .ordinal = 2, .is_z = false } },
    .{ .prime = 27, .number = .{ .cardinality = 4, .ordinal = 3, .is_z = false } },
    .{ .prime = 39, .number = .{ .cardinality = 4, .ordinal = 4, .is_z = false } },
    .{ .prime = 71, .number = .{ .cardinality = 4, .ordinal = 5, .is_z = false } },
    .{ .prime = 135, .number = .{ .cardinality = 4, .ordinal = 6, .is_z = false } },
    .{ .prime = 51, .number = .{ .cardinality = 4, .ordinal = 7, .is_z = false } },
    .{ .prime = 99, .number = .{ .cardinality = 4, .ordinal = 8, .is_z = false } },
    .{ .prime = 195, .number = .{ .cardinality = 4, .ordinal = 9, .is_z = false } },
    .{ .prime = 45, .number = .{ .cardinality = 4, .ordinal = 10, .is_z = false } },
    .{ .prime = 43, .number = .{ .cardinality = 4, .ordinal = 11, .is_z = false } },
    .{ .prime = 77, .number = .{ .cardinality = 4, .ordinal = 12, .is_z = false } },
    .{ .prime = 75, .number = .{ .cardinality = 4, .ordinal = 13, .is_z = false } },
    .{ .prime = 141, .number = .{ .cardinality = 4, .ordinal = 14, .is_z = false } },
    .{ .prime = 83, .number = .{ .cardinality = 4, .ordinal = 15, .is_z = true } },
    .{ .prime = 163, .number = .{ .cardinality = 4, .ordinal = 16, .is_z = false } },
    .{ .prime = 153, .number = .{ .cardinality = 4, .ordinal = 17, .is_z = false } },
    .{ .prime = 147, .number = .{ .cardinality = 4, .ordinal = 18, .is_z = false } },
    .{ .prime = 275, .number = .{ .cardinality = 4, .ordinal = 19, .is_z = false } },
    .{ .prime = 291, .number = .{ .cardinality = 4, .ordinal = 20, .is_z = false } },
    .{ .prime = 85, .number = .{ .cardinality = 4, .ordinal = 21, .is_z = false } },
    .{ .prime = 149, .number = .{ .cardinality = 4, .ordinal = 22, .is_z = false } },
    .{ .prime = 165, .number = .{ .cardinality = 4, .ordinal = 23, .is_z = false } },
    .{ .prime = 277, .number = .{ .cardinality = 4, .ordinal = 24, .is_z = false } },
    .{ .prime = 325, .number = .{ .cardinality = 4, .ordinal = 25, .is_z = false } },
    .{ .prime = 297, .number = .{ .cardinality = 4, .ordinal = 26, .is_z = false } },
    .{ .prime = 293, .number = .{ .cardinality = 4, .ordinal = 27, .is_z = false } },
    .{ .prime = 585, .number = .{ .cardinality = 4, .ordinal = 28, .is_z = false } },
    .{ .prime = 139, .number = .{ .cardinality = 4, .ordinal = 29, .is_z = true } },
    .{ .prime = 31, .number = .{ .cardinality = 5, .ordinal = 1, .is_z = false } },
    .{ .prime = 47, .number = .{ .cardinality = 5, .ordinal = 2, .is_z = false } },
    .{ .prime = 55, .number = .{ .cardinality = 5, .ordinal = 3, .is_z = false } },
    .{ .prime = 79, .number = .{ .cardinality = 5, .ordinal = 4, .is_z = false } },
    .{ .prime = 143, .number = .{ .cardinality = 5, .ordinal = 5, .is_z = false } },
    .{ .prime = 103, .number = .{ .cardinality = 5, .ordinal = 6, .is_z = false } },
    .{ .prime = 199, .number = .{ .cardinality = 5, .ordinal = 7, .is_z = false } },
    .{ .prime = 93, .number = .{ .cardinality = 5, .ordinal = 8, .is_z = false } },
    .{ .prime = 87, .number = .{ .cardinality = 5, .ordinal = 9, .is_z = false } },
    .{ .prime = 91, .number = .{ .cardinality = 5, .ordinal = 10, .is_z = false } },
    .{ .prime = 157, .number = .{ .cardinality = 5, .ordinal = 11, .is_z = false } },
    .{ .prime = 107, .number = .{ .cardinality = 5, .ordinal = 12, .is_z = true } },
    .{ .prime = 279, .number = .{ .cardinality = 5, .ordinal = 13, .is_z = false } },
    .{ .prime = 167, .number = .{ .cardinality = 5, .ordinal = 14, .is_z = false } },
    .{ .prime = 327, .number = .{ .cardinality = 5, .ordinal = 15, .is_z = false } },
    .{ .prime = 155, .number = .{ .cardinality = 5, .ordinal = 16, .is_z = false } },
    .{ .prime = 283, .number = .{ .cardinality = 5, .ordinal = 17, .is_z = true } },
    .{ .prime = 179, .number = .{ .cardinality = 5, .ordinal = 18, .is_z = true } },
    .{ .prime = 203, .number = .{ .cardinality = 5, .ordinal = 19, .is_z = false } },
    .{ .prime = 395, .number = .{ .cardinality = 5, .ordinal = 20, .is_z = false } },
    .{ .prime = 307, .number = .{ .cardinality = 5, .ordinal = 21, .is_z = false } },
    .{ .prime = 403, .number = .{ .cardinality = 5, .ordinal = 22, .is_z = false } },
    .{ .prime = 173, .number = .{ .cardinality = 5, .ordinal = 23, .is_z = false } },
    .{ .prime = 171, .number = .{ .cardinality = 5, .ordinal = 24, .is_z = false } },
    .{ .prime = 301, .number = .{ .cardinality = 5, .ordinal = 25, .is_z = false } },
    .{ .prime = 309, .number = .{ .cardinality = 5, .ordinal = 26, .is_z = false } },
    .{ .prime = 299, .number = .{ .cardinality = 5, .ordinal = 27, .is_z = false } },
    .{ .prime = 333, .number = .{ .cardinality = 5, .ordinal = 28, .is_z = false } },
    .{ .prime = 331, .number = .{ .cardinality = 5, .ordinal = 29, .is_z = false } },
    .{ .prime = 339, .number = .{ .cardinality = 5, .ordinal = 30, .is_z = false } },
    .{ .prime = 587, .number = .{ .cardinality = 5, .ordinal = 31, .is_z = false } },
    .{ .prime = 595, .number = .{ .cardinality = 5, .ordinal = 32, .is_z = false } },
    .{ .prime = 341, .number = .{ .cardinality = 5, .ordinal = 33, .is_z = false } },
    .{ .prime = 597, .number = .{ .cardinality = 5, .ordinal = 34, .is_z = false } },
    .{ .prime = 661, .number = .{ .cardinality = 5, .ordinal = 35, .is_z = false } },
    .{ .prime = 151, .number = .{ .cardinality = 5, .ordinal = 36, .is_z = true } },
    .{ .prime = 313, .number = .{ .cardinality = 5, .ordinal = 37, .is_z = true } },
    .{ .prime = 295, .number = .{ .cardinality = 5, .ordinal = 38, .is_z = true } },
    .{ .prime = 63, .number = .{ .cardinality = 6, .ordinal = 1, .is_z = false } },
    .{ .prime = 95, .number = .{ .cardinality = 6, .ordinal = 2, .is_z = false } },
    .{ .prime = 111, .number = .{ .cardinality = 6, .ordinal = 3, .is_z = true } },
    .{ .prime = 119, .number = .{ .cardinality = 6, .ordinal = 4, .is_z = true } },
    .{ .prime = 207, .number = .{ .cardinality = 6, .ordinal = 5, .is_z = false } },
    .{ .prime = 231, .number = .{ .cardinality = 6, .ordinal = 6, .is_z = true } },
    .{ .prime = 455, .number = .{ .cardinality = 6, .ordinal = 7, .is_z = false } },
    .{ .prime = 189, .number = .{ .cardinality = 6, .ordinal = 8, .is_z = false } },
    .{ .prime = 175, .number = .{ .cardinality = 6, .ordinal = 9, .is_z = false } },
    .{ .prime = 187, .number = .{ .cardinality = 6, .ordinal = 10, .is_z = true } },
    .{ .prime = 183, .number = .{ .cardinality = 6, .ordinal = 11, .is_z = true } },
    .{ .prime = 215, .number = .{ .cardinality = 6, .ordinal = 12, .is_z = true } },
    .{ .prime = 219, .number = .{ .cardinality = 6, .ordinal = 13, .is_z = true } },
    .{ .prime = 315, .number = .{ .cardinality = 6, .ordinal = 14, .is_z = false } },
    .{ .prime = 311, .number = .{ .cardinality = 6, .ordinal = 15, .is_z = false } },
    .{ .prime = 371, .number = .{ .cardinality = 6, .ordinal = 16, .is_z = false } },
    .{ .prime = 407, .number = .{ .cardinality = 6, .ordinal = 17, .is_z = true } },
    .{ .prime = 423, .number = .{ .cardinality = 6, .ordinal = 18, .is_z = false } },
    .{ .prime = 411, .number = .{ .cardinality = 6, .ordinal = 19, .is_z = true } },
    .{ .prime = 819, .number = .{ .cardinality = 6, .ordinal = 20, .is_z = false } },
    .{ .prime = 349, .number = .{ .cardinality = 6, .ordinal = 21, .is_z = false } },
    .{ .prime = 343, .number = .{ .cardinality = 6, .ordinal = 22, .is_z = false } },
    .{ .prime = 365, .number = .{ .cardinality = 6, .ordinal = 23, .is_z = true } },
    .{ .prime = 347, .number = .{ .cardinality = 6, .ordinal = 24, .is_z = true } },
    .{ .prime = 363, .number = .{ .cardinality = 6, .ordinal = 25, .is_z = true } },
    .{ .prime = 427, .number = .{ .cardinality = 6, .ordinal = 26, .is_z = true } },
    .{ .prime = 603, .number = .{ .cardinality = 6, .ordinal = 27, .is_z = false } },
    .{ .prime = 619, .number = .{ .cardinality = 6, .ordinal = 28, .is_z = true } },
    .{ .prime = 843, .number = .{ .cardinality = 6, .ordinal = 29, .is_z = true } },
    .{ .prime = 715, .number = .{ .cardinality = 6, .ordinal = 30, .is_z = false } },
    .{ .prime = 811, .number = .{ .cardinality = 6, .ordinal = 31, .is_z = false } },
    .{ .prime = 693, .number = .{ .cardinality = 6, .ordinal = 32, .is_z = false } },
    .{ .prime = 685, .number = .{ .cardinality = 6, .ordinal = 33, .is_z = false } },
    .{ .prime = 683, .number = .{ .cardinality = 6, .ordinal = 34, .is_z = false } },
    .{ .prime = 1365, .number = .{ .cardinality = 6, .ordinal = 35, .is_z = false } },
    .{ .prime = 159, .number = .{ .cardinality = 6, .ordinal = 36, .is_z = true } },
    .{ .prime = 287, .number = .{ .cardinality = 6, .ordinal = 37, .is_z = true } },
    .{ .prime = 399, .number = .{ .cardinality = 6, .ordinal = 38, .is_z = true } },
    .{ .prime = 317, .number = .{ .cardinality = 6, .ordinal = 39, .is_z = true } },
    .{ .prime = 303, .number = .{ .cardinality = 6, .ordinal = 40, .is_z = true } },
    .{ .prime = 335, .number = .{ .cardinality = 6, .ordinal = 41, .is_z = true } },
    .{ .prime = 591, .number = .{ .cardinality = 6, .ordinal = 42, .is_z = true } },
    .{ .prime = 359, .number = .{ .cardinality = 6, .ordinal = 43, .is_z = true } },
    .{ .prime = 615, .number = .{ .cardinality = 6, .ordinal = 44, .is_z = true } },
    .{ .prime = 605, .number = .{ .cardinality = 6, .ordinal = 45, .is_z = true } },
    .{ .prime = 599, .number = .{ .cardinality = 6, .ordinal = 46, .is_z = true } },
    .{ .prime = 663, .number = .{ .cardinality = 6, .ordinal = 47, .is_z = true } },
    .{ .prime = 679, .number = .{ .cardinality = 6, .ordinal = 48, .is_z = true } },
    .{ .prime = 667, .number = .{ .cardinality = 6, .ordinal = 49, .is_z = true } },
    .{ .prime = 723, .number = .{ .cardinality = 6, .ordinal = 50, .is_z = true } },
    .{ .prime = 127, .number = .{ .cardinality = 7, .ordinal = 1, .is_z = false } },
    .{ .prime = 191, .number = .{ .cardinality = 7, .ordinal = 2, .is_z = false } },
    .{ .prime = 319, .number = .{ .cardinality = 7, .ordinal = 3, .is_z = false } },
    .{ .prime = 223, .number = .{ .cardinality = 7, .ordinal = 4, .is_z = false } },
    .{ .prime = 239, .number = .{ .cardinality = 7, .ordinal = 5, .is_z = false } },
    .{ .prime = 415, .number = .{ .cardinality = 7, .ordinal = 6, .is_z = false } },
    .{ .prime = 463, .number = .{ .cardinality = 7, .ordinal = 7, .is_z = false } },
    .{ .prime = 381, .number = .{ .cardinality = 7, .ordinal = 8, .is_z = false } },
    .{ .prime = 351, .number = .{ .cardinality = 7, .ordinal = 9, .is_z = false } },
    .{ .prime = 607, .number = .{ .cardinality = 7, .ordinal = 10, .is_z = false } },
    .{ .prime = 379, .number = .{ .cardinality = 7, .ordinal = 11, .is_z = false } },
    .{ .prime = 671, .number = .{ .cardinality = 7, .ordinal = 12, .is_z = true } },
    .{ .prime = 375, .number = .{ .cardinality = 7, .ordinal = 13, .is_z = false } },
    .{ .prime = 431, .number = .{ .cardinality = 7, .ordinal = 14, .is_z = false } },
    .{ .prime = 471, .number = .{ .cardinality = 7, .ordinal = 15, .is_z = false } },
    .{ .prime = 623, .number = .{ .cardinality = 7, .ordinal = 16, .is_z = false } },
    .{ .prime = 631, .number = .{ .cardinality = 7, .ordinal = 17, .is_z = true } },
    .{ .prime = 815, .number = .{ .cardinality = 7, .ordinal = 18, .is_z = true } },
    .{ .prime = 719, .number = .{ .cardinality = 7, .ordinal = 19, .is_z = false } },
    .{ .prime = 919, .number = .{ .cardinality = 7, .ordinal = 20, .is_z = false } },
    .{ .prime = 823, .number = .{ .cardinality = 7, .ordinal = 21, .is_z = false } },
    .{ .prime = 871, .number = .{ .cardinality = 7, .ordinal = 22, .is_z = false } },
    .{ .prime = 701, .number = .{ .cardinality = 7, .ordinal = 23, .is_z = false } },
    .{ .prime = 687, .number = .{ .cardinality = 7, .ordinal = 24, .is_z = false } },
    .{ .prime = 733, .number = .{ .cardinality = 7, .ordinal = 25, .is_z = false } },
    .{ .prime = 699, .number = .{ .cardinality = 7, .ordinal = 26, .is_z = false } },
    .{ .prime = 695, .number = .{ .cardinality = 7, .ordinal = 27, .is_z = false } },
    .{ .prime = 747, .number = .{ .cardinality = 7, .ordinal = 28, .is_z = false } },
    .{ .prime = 727, .number = .{ .cardinality = 7, .ordinal = 29, .is_z = false } },
    .{ .prime = 855, .number = .{ .cardinality = 7, .ordinal = 30, .is_z = false } },
    .{ .prime = 731, .number = .{ .cardinality = 7, .ordinal = 31, .is_z = false } },
    .{ .prime = 859, .number = .{ .cardinality = 7, .ordinal = 32, .is_z = false } },
    .{ .prime = 1367, .number = .{ .cardinality = 7, .ordinal = 33, .is_z = false } },
    .{ .prime = 1371, .number = .{ .cardinality = 7, .ordinal = 34, .is_z = false } },
    .{ .prime = 1387, .number = .{ .cardinality = 7, .ordinal = 35, .is_z = false } },
    .{ .prime = 367, .number = .{ .cardinality = 7, .ordinal = 36, .is_z = true } },
    .{ .prime = 443, .number = .{ .cardinality = 7, .ordinal = 37, .is_z = true } },
    .{ .prime = 439, .number = .{ .cardinality = 7, .ordinal = 38, .is_z = true } },
    .{ .prime = 255, .number = .{ .cardinality = 8, .ordinal = 1, .is_z = false } },
    .{ .prime = 383, .number = .{ .cardinality = 8, .ordinal = 2, .is_z = false } },
    .{ .prime = 639, .number = .{ .cardinality = 8, .ordinal = 3, .is_z = false } },
    .{ .prime = 447, .number = .{ .cardinality = 8, .ordinal = 4, .is_z = false } },
    .{ .prime = 479, .number = .{ .cardinality = 8, .ordinal = 5, .is_z = false } },
    .{ .prime = 495, .number = .{ .cardinality = 8, .ordinal = 6, .is_z = false } },
    .{ .prime = 831, .number = .{ .cardinality = 8, .ordinal = 7, .is_z = false } },
    .{ .prime = 927, .number = .{ .cardinality = 8, .ordinal = 8, .is_z = false } },
    .{ .prime = 975, .number = .{ .cardinality = 8, .ordinal = 9, .is_z = false } },
    .{ .prime = 765, .number = .{ .cardinality = 8, .ordinal = 10, .is_z = false } },
    .{ .prime = 703, .number = .{ .cardinality = 8, .ordinal = 11, .is_z = false } },
    .{ .prime = 763, .number = .{ .cardinality = 8, .ordinal = 12, .is_z = false } },
    .{ .prime = 735, .number = .{ .cardinality = 8, .ordinal = 13, .is_z = false } },
    .{ .prime = 759, .number = .{ .cardinality = 8, .ordinal = 14, .is_z = false } },
    .{ .prime = 863, .number = .{ .cardinality = 8, .ordinal = 15, .is_z = true } },
    .{ .prime = 943, .number = .{ .cardinality = 8, .ordinal = 16, .is_z = false } },
    .{ .prime = 891, .number = .{ .cardinality = 8, .ordinal = 17, .is_z = false } },
    .{ .prime = 879, .number = .{ .cardinality = 8, .ordinal = 18, .is_z = false } },
    .{ .prime = 887, .number = .{ .cardinality = 8, .ordinal = 19, .is_z = false } },
    .{ .prime = 951, .number = .{ .cardinality = 8, .ordinal = 20, .is_z = false } },
    .{ .prime = 1375, .number = .{ .cardinality = 8, .ordinal = 21, .is_z = false } },
    .{ .prime = 1391, .number = .{ .cardinality = 8, .ordinal = 22, .is_z = false } },
    .{ .prime = 1455, .number = .{ .cardinality = 8, .ordinal = 23, .is_z = false } },
    .{ .prime = 1399, .number = .{ .cardinality = 8, .ordinal = 24, .is_z = false } },
    .{ .prime = 1495, .number = .{ .cardinality = 8, .ordinal = 25, .is_z = false } },
    .{ .prime = 1719, .number = .{ .cardinality = 8, .ordinal = 26, .is_z = false } },
    .{ .prime = 1463, .number = .{ .cardinality = 8, .ordinal = 27, .is_z = false } },
    .{ .prime = 1755, .number = .{ .cardinality = 8, .ordinal = 28, .is_z = false } },
    .{ .prime = 751, .number = .{ .cardinality = 8, .ordinal = 29, .is_z = true } },
    // Alternate prime encodings produced by transposition-only minimum-bit rotation.
    .{ .prime = 355, .number = .{ .cardinality = 5, .ordinal = 20, .is_z = false } },
    .{ .prime = 691, .number = .{ .cardinality = 6, .ordinal = 31, .is_z = false } },
    .{ .prime = 717, .number = .{ .cardinality = 6, .ordinal = 29, .is_z = false } },
    .{ .prime = 743, .number = .{ .cardinality = 7, .ordinal = 20, .is_z = false } },
    .{ .prime = 755, .number = .{ .cardinality = 7, .ordinal = 18, .is_z = true } },
    .{ .prime = 1467, .number = .{ .cardinality = 8, .ordinal = 26, .is_z = false } },
    .{ .prime = 511, .number = .{ .cardinality = 9, .ordinal = 1, .is_z = false } },
    .{ .prime = 767, .number = .{ .cardinality = 9, .ordinal = 2, .is_z = false } },
    .{ .prime = 895, .number = .{ .cardinality = 9, .ordinal = 3, .is_z = false } },
    .{ .prime = 959, .number = .{ .cardinality = 9, .ordinal = 4, .is_z = false } },
    .{ .prime = 991, .number = .{ .cardinality = 9, .ordinal = 5, .is_z = false } },
    .{ .prime = 1407, .number = .{ .cardinality = 9, .ordinal = 6, .is_z = false } },
    .{ .prime = 1471, .number = .{ .cardinality = 9, .ordinal = 7, .is_z = false } },
    .{ .prime = 1503, .number = .{ .cardinality = 9, .ordinal = 8, .is_z = false } },
    .{ .prime = 1519, .number = .{ .cardinality = 9, .ordinal = 9, .is_z = false } },
    .{ .prime = 1759, .number = .{ .cardinality = 9, .ordinal = 10, .is_z = false } },
    .{ .prime = 1775, .number = .{ .cardinality = 9, .ordinal = 11, .is_z = false } },
    .{ .prime = 1911, .number = .{ .cardinality = 9, .ordinal = 12, .is_z = false } },
};

pub fn lookup(prime: pcs.PitchClassSet) ?ForteNumber {
    for (ENTRIES) |entry| {
        if (entry.prime == prime) return entry.number;
    }
    return null;
}
